ok

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -65,6 +65,10 @@ jobs:
     - name: Get Kube config file
       run: aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER }}
 
+    - name: Delete existing secret if it exists
+      run: |
+        kubectl delete secret regcred || echo "Secret not found, proceeding."
+
     - name: Login to ECR
       run: |
         kubectl create secret docker-registry regcred \
